application:
  applicationType: dev
spring:
  profiles:
    active: dev
#rpcConfig
rpc:
  name: qi-rpc-core
  version: 1.0
  serverHost: localhost
  serverPort: 8080
  mock: false
  serializer: hessian
  registryConfig:
    registry: etcd
    address: http://localhost:2380
    username:
    password:
    timeout: 10004

